### ISSUE TITLE
Is this going to be deprecated?

### ISSUE THREAD

**Issue by voger** [elixircnx/openmaize#102]
Regarding your update in https://github.com/riverrun/openmaize/blob/master/README.md about using phauxth for phoenix 1.3. Does this mean this library is going to be abandoned and not maintained any more? Should we switch to phauxth from now on?

**Comment by riverrun** [comment]
I need to make it clearer in the README, but Openmaize is not going to be deprecated. I will continue to maintain it, but there probably won't be any new features added.

In addition, a lot depends on how long developers continue using Phoenix 1.2. About updating to Phoenix 1.3, my advice is to use Phauxth instead because certain design decisions have been made with Phoenix 1.3 in mind.
