### ISSUE TITLE
assign current_user with ecto struct

### ISSUE THREAD

**Issue by zhangsoledad** [elixircnx/openmaize#29]
openmaize/plugs/authenticate.ex:56

if i set config.repo and config.user_model, why not just assign current_user with ecto struct? like

``` elixir
  defp set_current_user({:ok, data}, conn) do
    case !!(Config.repo && Config.user_model) do
      true ->
        current_user = Config.repo.get(Config.user_model, data.id)
        assign(conn, :current_user, current_user)
      _ ->
        assign(conn, :current_user, data)
    end
  end
```

if ok ,i can PR with test

btw, need travis config?

**Comment by riverrun** [comment]
In answer to your question, it's because we're setting the current_user without a call to the database. The current_user is just based on the information in the JSON Web Token. We could possibly add it as an option - I'll think about that, and I'll let you know what I decide.

And about the travis config, well noticed :) I'll sort that out in the next few days.

**Comment by riverrun** [comment]
I've added travis support.
About assigning the current_user with an ecto struct, I think that the developer can do that just as easily at a later stage in the pipeline (in your controller, for example), so at the moment I'm not going to implement that.

**Comment by zhangsoledad** [comment]
ok , btw version 0.17 remove redirects  is  awesome, it become more easy to integrate .
