### ISSUE TITLE
Facebook, Twitter, ect... Oauth into Openmaize?

### ISSUE THREAD

**Issue by Pjino** [elixircnx/openmaize#83]
I know you had this planned but I'm wondering if you still plan to do it soon.
Thank you.

**Comment by riverrun** [comment]
This depends a lot on existing support for Oauth in Elixir. I'll look into it over the next few days.

**Comment by riverrun** [comment]
Unfortunately, I don't think this is going to happen any time soon. I don't really have the time.

Having said that, if anyone wants to send a pull request with Oauth2 support, I would be glad to add it to Openmaize.

If I get time to work on it in the future, I will reference this issue so that you will get a notification.

**Comment by Pjino** [comment]
OK.
Thank you.
